homeassistant:
  customize:
     switch.pumps:
       icon: mdi:water-pump
     switch.refillpump:
       friendly_name: Office Light
       icon: mdi:lightbulb
#       icon: mdi:water-pump
     switch.fan:
       icon: mdi:fan
     switch.wemo_insight:
       friendly_name: Fish Tank 2 Light
       icon: mdi:ceiling-light
     switch.wemo_switch_bedroom:
       friendly_name: Bedroom Light
       icon: mdi:lightbulb
     camera.officecam:
       friendly_name: 47g Tank Camera
     sensor.28051686b186ff:
       friendly_name: Room Temp
       icon: mdi:thermometer
     sensor.fishtanktemp:
       friendly_name: Fish Tank Temp
       icon: mdi:thermometer
     switch.living_room_light:
#       friendly_name: Fish Tank 2 Light
       icon: mdi:lightbulb
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 37.3537
  longitude: -122.0307
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 48
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
#config:

wemo:
  static:
    - 192.168.1.61
    - 192.168.1.29
    - 192.168.1.125
switch:
  -  platform: orvibo
     switches:
       -  host: 192.168.1.198
          name: "Fish Tank Pump"
       -  host: 192.168.1.204
          name: "Protein skimmer"
  - platform: mqtt
    name: "Skimmer"
    state_topic: "fishtank/skimmer/state"
    command_topic: "fishtank/skimmer/command"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    qos: 0
    retain: true
  - platform: mqtt
    name: "Fan"
    state_topic: "fishtank/fan/state"
    command_topic: "fishtank/fan/command"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    qos: 0
    retain: true
  - platform: mqtt
    name: "Pumps"
    state_topic: "fishtank/pumps/state"
    command_topic: "fishtank/pumps/command"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    qos: 0
    retain: true
  - platform: mqtt
    name: "refillpump"
    state_topic: "fishtank/refillpump/state"
    command_topic: "fishtank/refillpump/command"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    qos: 0
    retain: true
mqtt:
  broker:  192.168.1.188
  port: 1883
  keepalive: 60
#  client_id: HAmaster
  
#mqtt_eventstream:
#  subscribe_topic: hass_fishtank/#

#ffmpeg:
#  ffmpeg_bin: /usr/local/bin/ffmpeg

camera:
  - platform: rpi_camera
    name: living room
#    vertical_flip: 1
    image_rotation: 180
    timelapse: 2000
#    horizontal_flip: 1
    file_path:  /tmp/image.png
  - platform: generic
    still_image_url: http://192.168.1.210/mjpeg/snap.cgi?chn=0/snap.jpg
    name: officecam
    username: admin
    password: !secret cam_password
    authentication: digest
#  - platform: ffmpeg
#    input: rtsp:admin:123456@192.168.1.210/live/ch0
#    name: reefer 170

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret hass_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: yr
  - platform: rest
    resource: http://ip.jsontest.com
    name: External IP
    value_template: '{{ value_json.ip }}'
  - platform: time_date
    display_options:
      - 'date_time'
  - platform: onewire
#  - platform: command_line
#    name: fishtanktemp
#    command: "python3 /home/homeassistant/.homeassistant/querytanktemp.py"
#    unit_of_measurement: "C"
  - platform: mqtt
    state_topic: "fishtank/temperature"
    name: 'fishtanktemp'
    unit_of_measurement: 'F'
    value_template: '{{ value_json.temperature }}'

# Text to speech
#tts:
#  platform: google

group: !include groups.yaml

device_tracker:
  - platform: asuswrt
    host: 192.168.1.1
    username: admin
    password: !secret asusrt_password
    protocol: telnet
    consider_home: 180

automation:
 - alias: Light on when dark
   trigger: 
     platform: sun
     event: sunset
     offset: '-00:25:00'
   condition:
     condition: and
     conditions:
       - condition: state
         entity_id: 'device_tracker.android8ef561f60af42147'
         state: 'home'
   action:
     service: switch.turn_on
     entity_id: switch.living_room_light
automation 2:
 - alias: Auto turnoff
   trigger: 
     platform: time
     after: "02:30:00"
   action:
     -  service: switch.turn_off
        entity_id: switch.living_room_light
     -  service: media_player.turn_off
        data:
           entity_id: media_player.lgtv
automation 3:
 - alias: late night notify
   trigger: 
     platform: time
     after: "00:30:00"
   action:
     -  service: notify.lgtv2
        data:
           message: "It is 12:30"
automation 4:
 - alias: pump reminder
   trigger: 
     platform: time
     minutes: 5
     seconds: 00
   condition:
     condition: and
     conditions:
       - condition: state
         entity_id: 'device_tracker.robtu'
         state: 'not_home'
       - condition: or
         conditions:
           - condition: state
             entity_id: 'switch.fish_tank_pump'
             state: 'off'
           - condition: state
             entity_id: 'switch.living_room_light'
             state: 'on'
           - condition: state
             entity_id: 'switch.wemo_switch_bedroom'
             state: 'on'
#       - condition: state
#         entity_id: 'switch.fish_tank_pump'
#         state: 'off'
   action:
     -  service: notify.pushb
        data:
           message: "pumps are off or lights are on"
automation 5:
 - alias: Light on when home
   trigger: 
     platform: state
     entity_id: 'device_tracker.android8ef561f60af42147'
     to: 'home'
   condition:
     condition: sun
     after: sunset
     after_offset: '-00:25:00'
   action:
     service: switch.turn_on
     entity_id: switch.living_room_light
automation 6:
 - alias: turn off tv if forgot
   trigger: 
     platform: time
     minutes: 5
     seconds: 00
   condition:
     condition: and
     conditions:
       - condition: state
         entity_id: 'device_tracker.robtu'
         state: 'not_home'
       - condition: state
         entity_id: 'media_player.lgtv'
         state: 'on'
   action:
     -  service: notify.pushb
        data:
           message: "tv is still on"
automation 7:
 - alias: late late night notify
   trigger: 
     platform: time
     after: "01:00:00"
   action:
     -  service: notify.lgtv2
        data:
           message: "It is 1:00"
automation 8:
 - alias: high temperature alert
   trigger: 
     platform: time
     minutes: 30
     seconds: 00
   condition:
     condition: and
     conditions:
       - condition: numeric_state
         entity_id: 'sensor.28051686b186ff'
         above: '90'
   action:
     -  service: notify.pushb
        data:
           message: "Apt room temperature very high"
automation 9:
 - alias: tank temperature alert
   trigger: 
     platform: time
     minutes: 30
     seconds: 00
   condition:
     condition: and
     conditions:
       - condition: numeric_state
         entity_id: 'sensor.fishtanktemp'
         above: '85'
   action:
     -  service: notify.pushb
        data:
           message: "Fish Tank temperature very high"
    
automation 10:
 - alias: tank cold alert
   trigger: 
     platform: time
     minutes: 30
     seconds: 00
   condition:
     condition: and
     conditions:
       - condition: numeric_state
         entity_id: 'sensor.fishtanktemp'
         below: '75'
   action:
     -  service: notify.pushb
        data:
           message: "Fish Tank temperature too cold"
    
automation 11:
 - alias: tank fan off
   trigger: 
     platform: time
     minutes: 15
     seconds: 00
   condition:
     condition: and
     conditions:
       - condition: numeric_state
         entity_id: 'sensor.fishtanktemp'
         below: '80'
       - condition: state
         entity_id: 'switch.fan'
         state: 'on'
   action:
     -  service: switch.turn_off
        entity_id: switch.fan
automation 12:
 - alias: tank fan on
   trigger: 
     platform: time
     minutes: 15
     seconds: 00
   condition:
     condition: and
     conditions:
       - condition: numeric_state
         entity_id: 'sensor.fishtanktemp'
         above: '81'
       - condition: state
         entity_id: 'switch.fan'
         state: 'off'
   action:
     -  service: notify.pushb
        data:
           message: "Fish Tank temperature very high. Turning on fan"
     -  service: switch.turn_on
        entity_id: switch.fan
    
automation 13:
 - alias: protein skimmer on
   trigger: 
     platform: time
     at: '00:30:00'
   condition:
     condition: and
     conditions:
       - condition: numeric_state
         entity_id: 'sensor.fishtanktemp'
         below: '81'
   action:
     -  service: switch.turn_on
        entity_id: switch.skimmer
automation 14:
 - alias: protein skimmer off
   trigger: 
     platform: time
     at: '07:30:00'
   action:
     -  service: switch.turn_off
        entity_id: switch.skimmer
automation 15:
 - alias: auto refill water
   trigger: 
     platform: state
     entity_id: switch.refillpump
     to: 'on'
   action:
     -  service: script.turn_on
        entity_id: script.refill_timer
 - alias: auto refill reset
   trigger: 
     platform: state
     entity_id: switch.refillpump
     to: 'off'
   action:
     -  service: script.turn_off
        entity_id: script.refill_timer
  

#automation 2:
#   trigger:
#     platform: time
#     minutes: '/5'
#     seconds: 00
#   condition:
#     platform: sun
#     after: sunset
#     offset: '-00:20:00'
#   action:
#   - service: switch.turnon
#   entity_id: switch.living_room_light

media_player: 
  - platform: webostv
    host: 192.168.1.12 
    mac: C8:08:E9:ED:DD:AF
    name: lgtv
    filename: webostv.conf
notify:
  - platform: webostv
    host: 192.168.1.12 
    name: lgtv2
    filename: webostv.conf
  - name: pushb 
    platform: pushbullet
    api_key: !secret pushapi

shell_command:
#   recordtivo: /home/homeassistant/.homeassistant/tivoscript/RECORD
   recordtivo: /home/homeassistant/.homeassistant/githubdownload/pylgtv/tivorecord.py
   tivo5: /home/homeassistant/.homeassistant/tivoscript/NUM5
   tivopause: /home/homeassistant/.homeassistant/tivoscript/PAUSE
   tivoplay: /home/homeassistant/.homeassistant/tivoscript/PLAY
   tvpause: /home/homeassistant/.homeassistant/githubdownload/pylgtv/pause.py
   tvmute: /home/homeassistant/.homeassistant/githubdownload/pylgtv/mute.py
   tvunmute: /home/homeassistant/.homeassistant/githubdownload/pylgtv/unmute.py
   tvplay: /home/homeassistant/.homeassistant/githubdownload/pylgtv/play.py
   tivoadvance: /home/homeassistant/.homeassistant/tivoscript/ADVANCE
   abctv: /home/homeassistant/.homeassistant/githubdownload/pylgtv/channel.py 1_35_7_1_0_0_0
   foxtv: /home/homeassistant/.homeassistant/githubdownload/pylgtv/channel.py 1_48_2_1_0_0_0
   changevolhi: /home/homeassistant/.homeassistant/githubdownload/pylgtv/volume.py 30
   changevolmed: /home/homeassistant/.homeassistant/githubdownload/pylgtv/volume.py 17
   changevollo: /home/homeassistant/.homeassistant/githubdownload/pylgtv/volume.py 12
   tivo1: /home/homeassistant/.homeassistant/tivoscript/NUM1
   tivo4: /home/homeassistant/.homeassistant/tivoscript/NUM4
   tivo2: /home/homeassistant/.homeassistant/tivoscript/NUM2
   tivo3: /home/homeassistant/.homeassistant/tivoscript/NUM3
   tivo6: /home/homeassistant/.homeassistant/tivoscript/NUM6
   tivo7: /home/homeassistant/.homeassistant/tivoscript/NUM7
   tivo8: /home/homeassistant/.homeassistant/tivoscript/NUM8
   tivo9: /home/homeassistant/.homeassistant/tivoscript/NUM9
   tivo0: /home/homeassistant/.homeassistant/tivoscript/NUM0
   tivoenter: /home/homeassistant/.homeassistant/tivoscript/ENTER
   tivoright: /home/homeassistant/.homeassistant/tivoscript/RIGHT
   tivoguide: /home/homeassistant/.homeassistant/tivoscript/GUIDE
   tivolivetv: /home/homeassistant/.homeassistant/tivoscript/LIVETV
   restart_ha: systemctl restart home-assistant@homeassistant
   kodi: kodi &
#   relay16on: curl -k "http://192.168.1.189/relay16on.php"
#   relay16off: curl -k "http://192.168.1.189/relay16off.php"
#   relay20on: curl -k "http://192.168.1.189/relay20on.php"
#   relay20off: curl -k "http://192.168.1.189/relay20off.php"
#   relay21on: curl -k "http://192.168.1.189/relay21on.php"
#   relay21off: curl -k "http://192.168.1.189/relay21off.php"

script:
   home_theater:
     sequence:
       -  service: switch.turn_off
          data:
            entity_id: switch.wemo_insight
       -  service: media_player.turn_on
          data:
             entity_id: media_player.lgtv
       -  service: media_player.select_source
          data:
            entity_id: media_player.lgtv
            source: "Home Theater"
       -  service: switch.turn_off
          data:
            entity_id: switch.living_room_light
   home_theater_lights:
     sequence:
       -  service: switch.turn_off
          data:
            entity_id: switch.wemo_insight
       -  service: switch.turn_off
          data:
            entity_id: switch.living_room_light
   abcontv:
     sequence:
       -  service: media_player.turn_on
          data:
             entity_id: media_player.lgtv
       -  service: media_player.select_source
          data:
            entity_id: media_player.lgtv
            source: "livetv"
       -  service: shell_command.abctv
   cbsontv:
     sequence:
       -  service: media_player.turn_on
          data:
             entity_id: media_player.lgtv
       -  service: media_player.select_source
       -  delay:  00:00:01
       -  service: shell_command.tivo5
       -  service: shell_command.tivoadvance
       -  service: shell_command.tivo1
       -  service: shell_command.tivoenter
   telemundoontv:
     sequence:
       -  service: media_player.turn_on
          data:
             entity_id: media_player.lgtv
       -  service: media_player.select_source
          data:
            entity_id: media_player.lgtv
            source: "Set-top Box"
       -  service: shell_command.tivo4
       -  delay:  00:00:01
       -  service: shell_command.tivo8
       -  service: shell_command.tivoadvance
       -  service: shell_command.tivo1
       -  service: shell_command.tivoenter
   univisionontv:
     sequence:
       -  service: media_player.turn_on
          data:
             entity_id: media_player.lgtv
       -  service: media_player.select_source
          data:
            entity_id: media_player.lgtv
            source: "Set-top Box"
       -  service: shell_command.tivo1
       -  delay:  00:00:01
       -  service: shell_command.tivo4
       -  delay:  00:00:01
       -  service: shell_command.tivoadvance
       -  service: shell_command.tivo2
       -  service: shell_command.tivoenter
   restart:
     sequence:
       -  service: homeassistant.restart
#       -  service: shell_command.restart_ha
   recordscript:
     sequence:
       -  service: shell_command.recordtivo
#       -  delay:  00:00:01
#       -  service: shell_command.tivoright
   turnoffall:
     sequence:
       -  service: switch.turn_off
          data:
             entity_id: switch.living_room_light
       -  service: media_player.turn_off
          data:
             entity_id: media_player.lgtv
   turnofftv:
     sequence:
       -  service: media_player.turn_off
          data:
             entity_id: media_player.lgtv
   turnontv:
     sequence:
       -  service: media_player.turn_on
          data:
             entity_id: media_player.lgtv
   pbsontv:
     sequence:
       -  service: media_player.turn_on
          data:
             entity_id: media_player.lgtv
       -  service: media_player.select_source
          data:
            entity_id: media_player.lgtv
            source: "Set-top Box"
       -  service: shell_command.tivo9
       -  delay:  00:00:01
       -  service: shell_command.tivoadvance
       -  service: shell_command.tivo1
       -  service: shell_command.tivoenter
   kodiontv:
     sequence:
       -  service: media_player.turn_on
          data:
             entity_id: media_player.lgtv
       -  service: media_player.select_source
          data:
            entity_id: media_player.lgtv
            source: "kodi"
       -  service: shell_command.kodi
   pauseontv:
     sequence:
       -  service: shell_command.tivopause
#       -  service: shell_command.tvpause
       -  service: media_player.media_pause
          data:
             entity_id: media_player.lgtv
   playontv:
     sequence:
       -  service: shell_command.tivoplay
#       -  service: shell_command.tvplay
       -  service: media_player.media_play
          data:
             entity_id: media_player.lgtv
   missedtv:
     sequence:
       -  service: notify.lgtv2
          data:
             message: "missed phonecall"
   missedtext:
     sequence:
       -  service: notify.lgtv2
          data:
             message: "missed text"
   refill_timer:
     alias: "Refill Timer"
     sequence:
       -  delay:  '00:{{ states.input_slider.refill_run_time.state | int }}:00'
       -  service: homeassistant.turn_off
          data:
             entity_id: switch.refillpump
input_slider:
  refill_run_time:
    name: Refill Run Time
    initial: 5
    min: 1
    max: 15
    step: 1
