homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 37.3537
  longitude: -122.0307
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 48
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
#config:

switch:
  -  platform: orvibo
     switches:
       -  host: 192.168.1.198
          name: "Fish Tank Pump"
       -  host: 192.168.1.204
          name: "Protein skimmer"


http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret hass_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: yr
  - platform: rest
    resource: http://ip.jsontest.com
    name: External IP
    value_template: '{{ value_json.ip }}'

# Text to speech
#tts:
#  platform: google

group: !include groups.yaml

device_tracker:
  - platform: asuswrt
    host: 192.168.1.1
    username: admin
    password: !secret asusrt_password
    protocol: telnet
    consider_home: 180

automation:
 - alias: Light on when home
   trigger: 
    platform: sun
    event: sunset
    offset: '-00:20:00'
   condition:
     condition: and
     conditions:
       - condition: state
         entity_id: 'device_tracker.robtu'
         state: 'home'
   action:
     service: switch.turn_on
     entity_id: switch.wemo_living_room_light
automation 2:
 - alias: Auto turnoff
   trigger: 
     platform: time
     after: "02:30:00"
   action:
     -  service: switch.turn_off
        entity_id: switch.wemo_living_room_light
     -  service: media_player.turn_off
        data:
           entity_id: media_player.lgtv
automation 3:
 - alias: late night notify
   trigger: 
     platform: time
     after: "00:30:00"
   action:
     -  service: notify.lgtv
        data:
           message: "It is 12:30"
automation 4:
 - alias: pump reminder
   trigger: 
     platform: time
     minutes: 5
     seconds: 00
   condition:
     condition: and
     conditions:
       - condition: state
         entity_id: 'device_tracker.robtu'
         state: 'not_home'
       - condition: state
         entity_id: 'switch.fish_tank_pump'
         state: 'off'
   action:
     -  service: notify.pushb
        data:
           message: "pumps are off"
    

#automation 2:
#   trigger:
#     platform: time
#     minutes: '/5'
#     seconds: 00
#   condition:
#     platform: sun
#     after: sunset
#     offset: '-00:20:00'
#   action:
#   - service: switch.turnon
#   entity_id: switch.wemo_living_room_light

media_player: 
  - platform: webostv
    host: 192.168.1.12 
    mac: C8:08:E9:ED:DD:AF
    name: lgtv
    filename: webostv.conf
notify:
  - platform: webostv
    host: 192.168.1.12 
    name: lgtv
    filename: webostv.conf
  - name: pushb 
    platform: pushbullet
    api_key: !secret pushapi

shell_command:
   recordtivo: /home/homeassistant/.homeassistant/tivoscript/RECORD
   tivo5: /home/homeassistant/.homeassistant/tivoscript/NUM5
   tivopause: /home/homeassistant/.homeassistant/tivoscript/PAUSE
   tivoplay: /home/homeassistant/.homeassistant/tivoscript/PLAY
   tvpause: /home/homeassistant/.homeassistant/githubdownload/pylgtv/pause.py
   tvplay: /home/homeassistant/.homeassistant/githubdownload/pylgtv/play.py
   tivoadvance: /home/homeassistant/.homeassistant/tivoscript/ADVANCE
   abctv: /home/homeassistant/.homeassistant/githubdownload/pylgtv/channel.py 1_35_7_1_0_0_0
   foxtv: /home/homeassistant/.homeassistant/githubdownload/pylgtv/channel.py 1_48_2_1_0_0_0
   changevolhi: /home/homeassistant/.homeassistant/githubdownload/pylgtv/volume.py 30
   changevolmed: /home/homeassistant/.homeassistant/githubdownload/pylgtv/volume.py 17
   changevollo: /home/homeassistant/.homeassistant/githubdownload/pylgtv/volume.py 12
   tivo1: /home/homeassistant/.homeassistant/tivoscript/NUM1
   tivo4: /home/homeassistant/.homeassistant/tivoscript/NUM4
   tivo2: /home/homeassistant/.homeassistant/tivoscript/NUM2
   tivo3: /home/homeassistant/.homeassistant/tivoscript/NUM3
   tivo6: /home/homeassistant/.homeassistant/tivoscript/NUM6
   tivo7: /home/homeassistant/.homeassistant/tivoscript/NUM7
   tivo8: /home/homeassistant/.homeassistant/tivoscript/NUM8
   tivo9: /home/homeassistant/.homeassistant/tivoscript/NUM9
   tivo0: /home/homeassistant/.homeassistant/tivoscript/NUM0
   tivoenter: /home/homeassistant/.homeassistant/tivoscript/ENTER
   tivoright: /home/homeassistant/.homeassistant/tivoscript/RIGHT
   restart_ha: systemctl restart home-assistant@homeassistant
   kodi: kodi &

script:
   home_theater:
     sequence:
       -  service: switch.turn_off
          data:
            entity_id: switch.wemo_living_room_light
#       -  service: switch.turn_off
#       entity_id: switch.living_room_tank
       -  service: media_player.turn_on
          data:
             entity_id: media_player.lgtv
       -  service: media_player.select_source
          data:
            entity_id: media_player.lgtv
            source: "Home Theater"
#   abcontv:
#     sequence:
#       -  service: media_player.select_source
#       entity_id: lgtv
#       source: "livetv"
#       -  service: media_player.play_media
#       entity_id: lgtv
#       media_content_type: "channel"
   cbsontv:
     sequence:
       -  service: media_player.turn_on
          data:
             entity_id: media_player.lgtv
       -  service: media_player.select_source
          data:
            entity_id: media_player.lgtv
            source: "Set-top Box"
       -  delay:  00:00:01
       -  service: shell_command.tivo5
       -  service: shell_command.tivoadvance
       -  service: shell_command.tivo1
       -  service: shell_command.tivoenter
   telemundoontv:
     sequence:
       -  service: media_player.turn_on
          data:
             entity_id: media_player.lgtv
       -  service: media_player.select_source
          data:
            entity_id: media_player.lgtv
            source: "Set-top Box"
       -  service: shell_command.tivo4
       -  delay:  00:00:01
       -  service: shell_command.tivo8
       -  service: shell_command.tivoadvance
       -  service: shell_command.tivo1
       -  service: shell_command.tivoenter
   univisionontv:
     sequence:
       -  service: media_player.turn_on
          data:
             entity_id: media_player.lgtv
       -  service: media_player.select_source
          data:
            entity_id: media_player.lgtv
            source: "Set-top Box"
       -  delay:  00:00:02
       -  service: shell_command.tivo1
       -  service: shell_command.tivo4
       -  service: shell_command.tivoadvance
       -  service: shell_command.tivo2
       -  service: shell_command.tivoenter
   restart:
     sequence:
       -  service: homeassistant.restart
#       -  service: shell_command.restart_ha
   recordscript:
     sequence:
       -  service: shell_command.recordtivo
       -  delay:  00:00:01
       -  service: shell_command.tivoright
   turnoffall:
     sequence:
       -  service: switch.turn_off
          data:
             entity_id: switch.wemo_living_room_light
       -  service: media_player.turn_off
          data:
             entity_id: media_player.lgtv
   turnofftv:
     sequence:
       -  service: media_player.turn_off
          data:
             entity_id: media_player.lgtv
   turnontv:
     sequence:
       -  service: media_player.turn_on
          data:
             entity_id: media_player.lgtv
   pbsontv:
     sequence:
       -  service: media_player.turn_on
          data:
             entity_id: media_player.lgtv
       -  service: media_player.select_source
          data:
            entity_id: media_player.lgtv
            source: "Set-top Box"
       -  service: shell_command.tivo9
       -  delay:  00:00:01
       -  service: shell_command.tivoadvance
       -  service: shell_command.tivo1
       -  service: shell_command.tivoenter
   kodiontv:
     sequence:
       -  service: media_player.turn_on
          data:
             entity_id: media_player.lgtv
       -  service: media_player.select_source
          data:
            entity_id: media_player.lgtv
            source: "kodi"
       -  service: shell_command.kodi
   pauseontv:
     sequence:
       -  service: shell_command.tivopause
#       -  service: shell_command.tvpause
       -  service: media_player.media_pause
          data:
             entity_id: media_player.lgtv
   playontv:
     sequence:
       -  service: shell_command.tivoplay
#       -  service: shell_command.tvplay
       -  service: media_player.media_play
          data:
             entity_id: media_player.lgtv

